export const SIDEBAR_WIDTH = 288;
export const TARGET_MIN_LEFT_PANE_WIDTH = 320;
export const TARGET_MIN_RIGHT_PANE_WIDTH = 420;
export const TARGET_COLUMN_RESIZER_WIDTH = 8;
export const TARGET_MIN_MAIN_WIDTH =
  TARGET_MIN_LEFT_PANE_WIDTH + TARGET_MIN_RIGHT_PANE_WIDTH + TARGET_COLUMN_RESIZER_WIDTH;
