/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./ui/components/friday/ActionCard.vue')['default']
    ActionModal: typeof import('./ui/components/friday/ActionModal.vue')['default']
    CodeEditor: typeof import('./ui/components/friday/CodeEditor.vue')['default']
    DiffEditor: typeof import('./ui/components/friday/DiffEditor.vue')['default']
    FridayChatDrawer: typeof import('./ui/components/friday/friday-chat-drawer.vue')['default']
    FridayChatInput: typeof import('./ui/components/friday/FridayChatInput.vue')['default']
    FridayContextPanel: typeof import('./ui/components/friday/FridayContextPanel.vue')['default']
    FridayMarkdown: typeof import('./ui/components/friday/FridayMarkdown.vue')['default']
    FridayMessageList: typeof import('./ui/components/friday/FridayMessageList.vue')['default']
    FridayTodoList: typeof import('./ui/components/friday/FridayTodoList.vue')['default']
    MonacoEditor: typeof import('./ui/components/MonacoEditor.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NInput: typeof import('naive-ui')['NInput']
    NotificationBridge: typeof import('./ui/components/NotificationBridge.vue')['default']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpin: typeof import('naive-ui')['NSpin']
    ReasoningBlock: typeof import('./ui/components/friday/ReasoningBlock.vue')['default']
    SettingsModal: typeof import('./ui/components/SettingsModal.vue')['default']
    Sidebar: typeof import('./ui/components/Sidebar.vue')['default']
    SuggestionsPanel: typeof import('./ui/components/friday/SuggestionsPanel.vue')['default']
    TargetView: typeof import('./ui/components/TargetView.vue')['default']
    TerminalPanel: typeof import('./ui/components/TerminalPanel.vue')['default']
    ToastNotification: typeof import('./ui/components/ToastNotification.vue')['default']
    ToolCallCard: typeof import('./ui/components/friday/ToolCallCard.vue')['default']
  }
}
