/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MonacoEditor: typeof import('./ui/components/MonacoEditor.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NInput: typeof import('naive-ui')['NInput']
    NotificationBridge: typeof import('./ui/components/NotificationBridge.vue')['default']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpin: typeof import('naive-ui')['NSpin']
    SettingsModal: typeof import('./ui/components/SettingsModal.vue')['default']
    Sidebar: typeof import('./ui/components/Sidebar.vue')['default']
    TargetView: typeof import('./ui/components/TargetView.vue')['default']
    TerminalPanel: typeof import('./ui/components/TerminalPanel.vue')['default']
    ToastNotification: typeof import('./ui/components/ToastNotification.vue')['default']
  }
}
